let suiviData = [
  {
    "representant": "Mme yasmina",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "ECOLE MONTESSORI",
    "contact": "709 23 80 68",
    "type_bien": "VILLA",
    "action": "location",
    "budget": 60000,
    "superficie": "",
    "zone": "",
    "type_accompagnement": "creation de la societe, business plan, commercialisation, gestion des travaux et amenagement, etude de marche, etude concurrentielle, marketing digital dossier de financement du projet",
    "prix_alloue": "",
    "services_clotures": "Proccuration, mandat exclusif de gestion, etude de marche, prospection, contrat de bail, devis des travaux et d'amenagement, creation de logos et image de marque",
    "services_a_cloturer": "l'autorisation d'exploitation, travaux, dossier de financement, business plan, marketing digital",
    "ok_nok": "OK",
    "annexes": "",
    "ca_previsionnel": 120000,
    "ca_realise": 100000,
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme HASSNA",
    "nom": "Atlas capital",
    "mode_retour": "site web",
    "activite": "Cabinet d'assurance",
    "contact": 662830415,
    "type_bien": "plateau bureau",
    "action": "location",
    "budget": 6100,
    "superficie": 54,
    "zone": "NEJMA",
    "type_accompagnement": "prospection",
    "prix_alloue": "",
    "services_clotures": "CONTRAT CLOTUREE",
    "services_a_cloturer": "RAS",
    "ok_nok": "OK",
    "annexes": "",
    "ca_previsionnel": 12200,
    "ca_realise": 12200,
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Rachid",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "promotion immobiliere",
    "contact": 33777373060,
    "type_bien": "TERRAIN",
    "action": "achat",
    "budget": "",
    "superficie": 400,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 0,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr EL BAKKOURI",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "RESTAURATION",
    "contact": 33609716096,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 10000,
    "superficie": 37,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "programme d'accompagnement",
    "prix_alloue": "",
    "services_clotures": "propositions, visites de trois locaux, signature des bons de visites et avis de recherche",
    "services_a_cloturer": "Visite sur place le 20/03/2024",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 20000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "zin eddine abidine",
    "nom": "",
    "mode_retour": "contact Mr karim",
    "activite": "promotion immobiliere",
    "contact": "44 7487 746205",
    "type_bien": "TERRAIN",
    "action": "achat",
    "budget": 2000000,
    "superficie": 1000,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee, visite sur place des terrains",
    "services_a_cloturer": "etude de faisabilite des terrains",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 4000000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Pause",
    "created_date": "2024/02/02",
    "update_date": "2024/02/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr TOUMI",
    "nom": "TANGER TECH",
    "mode_retour": "contact Mr karim",
    "activite": "",
    "contact": "636 06 04 73",
    "type_bien": "VILLA",
    "action": "location",
    "budget": 50000,
    "superficie": 600,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "recherche en cours",
    "services_a_cloturer": "propositions",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 100000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Anas",
    "nom": "",
    "mode_retour": "site web",
    "activite": "visite technique",
    "contact": 661175018,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 60000,
    "superficie": 400,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "recherche en cours",
    "services_a_cloturer": "propositions",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 120000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme HOUDA",
    "nom": "",
    "mode_retour": "sarouty",
    "activite": "produits cosmetics",
    "contact": 667079410,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 15000,
    "superficie": "",
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "recherche en cours",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 30000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr OMAR",
    "nom": "",
    "mode_retour": "sarouty",
    "activite": "creperie",
    "contact": 661146769,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 15000,
    "superficie": 60,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "visite sur place",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 30000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Hamza",
    "nom": "SEGULA TECHNOLOGIES",
    "mode_retour": "sarouty",
    "activite": "Bureau d'etudes",
    "contact": 663695805,
    "type_bien": "plateau bureau",
    "action": "location",
    "budget": "",
    "superficie": 300,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "visite programee la semaine du 15/04/2024",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 30000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Pause",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr ALAMI",
    "nom": "",
    "mode_retour": "site web",
    "activite": "COFFEE SHOP",
    "contact": 661419381,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 7000,
    "superficie": 30,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 0,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme Oumaima",
    "nom": "",
    "mode_retour": "site web",
    "activite": "maison individuelle",
    "contact": 668136660,
    "type_bien": "TERRAIN",
    "action": "achat",
    "budget": 7000,
    "superficie": "",
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 0,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/03/02",
    "update_date": "2024/03/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme Jihad",
    "nom": "",
    "mode_retour": "sarouty",
    "activite": "coworking space",
    "contact": 706017625,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 10000,
    "superficie": 100,
    "zone": "EL KASBAH",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee, visite client, negociation et preparation du contrat",
    "services_a_cloturer": "contrat signe le 29/05/2024",
    "ok_nok": "ok",
    "annexes": "",
    "ca_previsionnel": 20000,
    "ca_realise": 12000,
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme Hind",
    "nom": "Le Noble",
    "mode_retour": "sarouty",
    "activite": "boutique patisserie",
    "contact": 661066999,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 15000,
    "superficie": 100,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee, visite client, negociation, preparation des documents",
    "services_a_cloturer": "ko, desaccord par rapport aux documents",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": 30000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "",
    "nom": "restaurant chinois",
    "mode_retour": "sarouty",
    "activite": "RESTAURATION",
    "contact": 600952821,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 40000,
    "superficie": 180,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 80000,
    "ca_realise": "",
    "total_ca": "",
    "status": "Pause",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Tarik",
    "nom": "space m",
    "mode_retour": "contact Mr karim",
    "activite": "agence de communication",
    "contact": 688759545,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 17000,
    "superficie": 250,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 34000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme houda",
    "nom": "palace de fleur",
    "mode_retour": "sarouty",
    "activite": "fleuriste",
    "contact": 661553316,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 10000,
    "superficie": 30,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": 20000,
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme kamar",
    "nom": "",
    "mode_retour": "sarouty",
    "activite": "investissement",
    "contact": 666377601,
    "type_bien": "plateau bureau",
    "action": "achat",
    "budget": "",
    "superficie": 70,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme Malak",
    "nom": "",
    "mode_retour": "sarouty",
    "activite": "cabinet dentaire",
    "contact": "",
    "type_bien": "plateau bureau",
    "action": "location",
    "budget": 8000,
    "superficie": "",
    "zone": "",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "visite prevue le 24/02/2024",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Younes",
    "nom": "industrie",
    "mode_retour": "sarouty",
    "activite": "administration",
    "contact": "",
    "type_bien": "plateau bureau",
    "action": "location",
    "budget": 8000,
    "superficie": "",
    "zone": "centre ville",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Fouad",
    "nom": "l'ordre regional des comptables",
    "mode_retour": "contact asmaa",
    "activite": "administration",
    "contact": "",
    "type_bien": "plateau bureau",
    "action": "location",
    "budget": 10000,
    "superficie": 100,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee, visite client, negociation",
    "services_a_cloturer": "contrat signe le 30/04/2024",
    "ok_nok": "ok",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": 14320,
    "total_ca": "",
    "status": "Active",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Younes",
    "nom": "",
    "mode_retour": "sarouty",
    "activite": "RESTAURATION",
    "contact": 33661216210,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 13000,
    "superficie": 70,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Othamn",
    "nom": "AL ALMAAI GROUPE",
    "mode_retour": "sarouty",
    "activite": "gestion de patrimoine / gestion locative",
    "contact": 655466388,
    "type_bien": "bureau",
    "action": "location",
    "budget": 6000,
    "superficie": 50,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr Ismail",
    "nom": "FLM EXPRESS (flash maroc)",
    "mode_retour": "contact Mr karim",
    "activite": "transport",
    "contact": 661689017,
    "type_bien": "bureau",
    "action": "location",
    "budget": 7000,
    "superficie": 100,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee, visites des bureaux",
    "services_a_cloturer": "ko, sont plus interesses",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/04/02",
    "update_date": "2024/04/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "porteurs d'affaires",
    "nom": "",
    "mode_retour": "contact",
    "activite": "hypermarche",
    "contact": "",
    "type_bien": "locaux commerciaux",
    "action": "location",
    "budget": 25000,
    "superficie": 190,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/05/02",
    "update_date": "2024/05/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme Hafsa",
    "nom": "",
    "mode_retour": "contact",
    "activite": "cabinet dentaire",
    "contact": 680711971,
    "type_bien": "",
    "action": "location",
    "budget": "",
    "superficie": "",
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "pas de reponse",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/05/02",
    "update_date": "2024/05/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mr driss",
    "nom": "",
    "mode_retour": "contact",
    "activite": "RESTAURATION",
    "contact": "",
    "type_bien": "local",
    "action": "location",
    "budget": "",
    "superficie": 1500,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "pas de reponse",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/05/02",
    "update_date": "2024/05/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme maryem",
    "nom": "",
    "mode_retour": "contact",
    "activite": "onglerie",
    "contact": 661181653,
    "type_bien": "local",
    "action": "location",
    "budget": "",
    "superficie": 100,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "pas de reponse",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/05/02",
    "update_date": "2024/05/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "",
    "nom": "",
    "mode_retour": "Sarouty",
    "activite": "RESTAURATION",
    "contact": "33 7 49 99 43 09",
    "type_bien": "local",
    "action": "location",
    "budget": 50000,
    "superficie": 400,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/05/02",
    "update_date": "2024/05/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "",
    "nom": "beauty-woow",
    "mode_retour": "Sarouty",
    "activite": "centre de beaute",
    "contact": "670 706207",
    "type_bien": "local",
    "action": "location",
    "budget": 50000,
    "superficie": 600,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "pas de reponse",
    "ok_nok": "non",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "Blocker",
    "created_date": "2024/05/02",
    "update_date": "2024/05/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "COMPTABLE PFC",
    "nom": "",
    "mode_retour": "COLLABORATION",
    "activite": "BUREAU",
    "contact": "",
    "type_bien": "BUREAU",
    "action": "ACHAT",
    "budget": "",
    "superficie": 60,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/05/02",
    "update_date": "2024/05/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme NAIMA",
    "nom": "call-center",
    "mode_retour": "Sarouty",
    "activite": "CALL-CENTER",
    "contact": "697 748 418",
    "type_bien": "BUREAU",
    "action": "location",
    "budget": 8000,
    "superficie": 60,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/06/02",
    "update_date": "2024/06/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme Hind",
    "nom": "Le Noble",
    "mode_retour": "CONTACT",
    "activite": "boutique patisserie",
    "contact": 661066999,
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": 15000,
    "superficie": 50,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "PROSPECTION",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/06/02",
    "update_date": "2024/06/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "ARCHITECTE MK",
    "nom": "",
    "mode_retour": "COLLABORATION",
    "activite": "promotion immobiliere",
    "contact": "",
    "type_bien": "TERRAIN",
    "action": "ACHAT",
    "budget": "15 000 000",
    "superficie": 800,
    "zone": "",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/06/02",
    "update_date": "2024/06/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Mme Nissrine",
    "nom": "chocolaxy",
    "mode_retour": "Sarouty",
    "activite": "patisserie",
    "contact": "661 493 542",
    "type_bien": "LOCAL COMMERCIAL",
    "action": "location",
    "budget": "15 000",
    "superficie": 80,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/06/02",
    "update_date": "2024/06/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "ARCHITECTE MEHDI BARAKAT",
    "nom": "",
    "mode_retour": "COLLABORATION",
    "activite": "STOCKAGE",
    "contact": "",
    "type_bien": "HANGAR",
    "action": "location",
    "budget": "",
    "superficie": "",
    "zone": "LA ZONE INDUSTRIELLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/06/02",
    "update_date": "2024/06/02",
    "": "",
    "__1": "",
    "__2": ""
  },
  {
    "representant": "Cabinet AUDINORD",
    "nom": "AUDINORD",
    "mode_retour": "RESEAU",
    "activite": "CABINET DE COMPTABILITE",
    "contact": "",
    "type_bien": "PLATEAU BUREAU",
    "action": "location",
    "budget": "",
    "superficie": 200,
    "zone": "CENTRE VILLE",
    "type_accompagnement": "",
    "prix_alloue": "",
    "services_clotures": "proposition envoyee",
    "services_a_cloturer": "",
    "ok_nok": "",
    "annexes": "",
    "ca_previsionnel": "",
    "ca_realise": "",
    "total_ca": "",
    "status": "A faire",
    "created_date": "2024/06/02",
    "update_date": "2024/06/02",
    "": "",
    "__1": "",
    "__2": ""
  }
];

export default suiviData;
